# Generated by Django 4.1.1 on 2022-09-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postagem',
            name='post_imagem',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
